<?php

return [
    'list' => [
        ['name' => 'Pet Supplies', 'icon' => 'paw', 'subcategories' => [
            'Dog Food & Treats',
            'Cat Litter & Accessories',
            'Aquariums & Fish Supplies',
            'Bird Feeders & Food',
            'Pet Grooming Products',
            'Pet Health & Wellness',
        ]],
        ['name' => 'Electronics and Gadgets', 'icon' => 'device', 'subcategories' => [
            'Mobile Phones & Accessories',
            'Laptops, Desktops & Monitors',
            'Audio & Video Equipment',
            'Smart Home Devices',
            'Cameras & Photography',
            'Wearable Technology',
        ]],
        ['name' => "Women's Apparel", 'icon' => 'dress', 'subcategories' => [
            'Dresses & Skirts',
            'Tops & Blouses',
            'Activewear & Yoga Pants',
            'Lingerie & Sleepwear',
            'Jackets & Coats',
            'Shoes & Accessories',
        ]],
        ['name' => "Men's Apparel", 'icon' => 'shirt', 'subcategories' => [
            'Suits & Blazers',
            'Casual Shirts & Pants',
            'Outerwear & Jackets',
            'Activewear & Fitness Gear',
            'Shoes & Accessories',
            'Grooming Products',
        ]],
        ['name' => 'Kids and Baby', 'icon' => 'baby', 'subcategories' => [
            'Baby Clothes & Accessories',
            'Toys & Games',
            'Educational Materials',
            'Strollers & Gear',
            'Nursery Furniture',
            'Safety and Health',
        ]],
        ['name' => 'Home and Garden', 'icon' => 'home', 'subcategories' => [
            'Kitchen Appliances',
            'Furniture & Decor',
            'Gardening Tools',
            'Outdoor Living',
            'Home Improvement Tools',
            'Bedding & Bath',
        ]],
        ['name' => 'Sports and Outdoors', 'icon' => 'ball', 'subcategories' => [
            'Fitness Equipment',
            'Camping & Hiking Gear',
            'Sports Apparel',
            'Cycling & Bikes',
            'Water Sports',
            'Team Sports Equipment',
        ]],
        ['name' => 'Health and Beauty', 'icon' => 'heart', 'subcategories' => [
            'Skincare Products',
            'Haircare Solutions',
            'Makeup & Cosmetics',
            'Personal Care Appliances',
            "Men's Grooming",
            'Health Supplements',
        ]],
        ['name' => 'Books and Media', 'icon' => 'book', 'subcategories' => [
            'Fiction & Non-Fiction Books',
            'Magazines & Periodicals',
            'Music CDs & Vinyl Records',
            'Movie DVDs & Blu-ray',
            'Video Games & Consoles',
            'Educational DVDs',
        ]],
        ['name' => 'Food and Gourmet', 'icon' => 'food', 'subcategories' => [
            'Baking Supplies & Ingredients',
            'Coffee, Tea & Beverages',
            'Snacks & Candy',
            'Specialty Foods & International Cuisine',
            'Organic and Health Foods',
            'Meal Kits & Prepped Foods',
        ]],
        ['name' => 'Automotive & Motorcycle', 'icon' => 'car', 'subcategories' => [
            'Protective Gear',
            'Maintenance & Repair Tools',
            'Parts & Accessories',
            'Electrical Components',
            'Tires, Wheels, and Fluids',
        ]],
        ['name' => 'Furniture and Office Equipment', 'icon' => 'office', 'subcategories' => [
            'Office Desks & Chairs',
            'Storage Cabinets & Shelving',
            'Conference & Meeting Furniture',
            'Computer Tables & Workstations',
            'Ergonomic Accessories',
            'Office Lighting & Fixtures',
        ]],
        ['name' => 'Jewelry and Watches', 'icon' => 'gem', 'subcategories' => [
            'Necklaces & Pendants',
            'Rings & Earrings',
            'Bracelets & Bangles',
            'Watches for Men & Women',
            'Fashion Jewelry',
            'Jewelry Storage & Care',
        ]],
        ['name' => 'Office and School Supplies', 'icon' => 'pencil', 'subcategories' => [
            'Notebooks & Paper Products',
            'Writing Instruments',
            'Office Furniture',
            'Printers & Printing Supplies',
            'School Bags & Backpacks',
            'Arts & Craft Materials',
        ]],
    ],
];
